package com.karaokeflow.app;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.Color; import android.net.Uri; import android.graphics.drawable.GradientDrawable; import android.view.*; import android.widget.*; import java.io.*; import java.util.*;

public class MainActivity extends Activity {
 static final int CSV=1,FOLDER=2,SF2=3; final ArrayList<Song> songs=new ArrayList<>(); LinearLayout list; EditText search; TextView status;
 static class Song { int id; String title,artist,file; Song(int i,String t,String a,String f){id=i;title=t;artist=a;file=f;} }
 int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(dp(5),dp(6),dp(5),dp(6));return v;}
 public void onCreate(Bundle b){super.onCreate(b); ScrollView sc=new ScrollView(this); LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(30));root.setBackgroundColor(Color.rgb(8,11,18));sc.addView(root);setContentView(sc);
  TextView brand=tv("KaraokeFlow",30,Color.WHITE);brand.setTypeface(null,1);root.addView(brand);root.addView(tv("Your songs. Your stage.",14,0xff9da3b5));
  search=new EditText(this);search.setHint("Search title, artist or song #");search.setHintTextColor(0xff777e95);search.setTextColor(Color.WHITE);search.setSingleLine();search.setBackground(bg(0xff181c2a,18));search.setPadding(dp(16),0,dp(16),0);LinearLayout.LayoutParams qp=new LinearLayout.LayoutParams(-1,dp(54));qp.setMargins(0,dp(18),0,dp(12));root.addView(search,qp);
  search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){render(s.toString());}public void afterTextChanged(android.text.Editable e){}});
  LinearLayout row=new LinearLayout(this);row.addView(btn("Import CSV",CSV),new LinearLayout.LayoutParams(0,dp(48),1));row.addView(btn("MIDI Folder",FOLDER),new LinearLayout.LayoutParams(0,dp(48),1));row.addView(btn("SoundFont",SF2),new LinearLayout.LayoutParams(0,dp(48),1));root.addView(row);
  status=tv("Import mkmd_catalog_probe.csv, choose SongHub_Extracted, then choose your .sf2.",13,0xffa5aabe);root.addView(status);TextView h=tv("Songs",20,Color.WHITE);h.setTypeface(null,1);root.addView(h);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);render(""); }
 Button btn(String s,int r){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setOnClickListener(v->{Intent i;if(r==FOLDER)i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);else{i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(r==CSV?"text/*":"*/*");}startActivityForResult(i,r);});return b;}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null||d.getData()==null)return;Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,d.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));}catch(Exception ignored){}if(r==CSV)load(u);else if(r==FOLDER){getPreferences(0).edit().putString("midi",u.toString()).apply();status.setText("MIDI folder selected.");}else{getPreferences(0).edit().putString("sf2",u.toString()).apply();status.setText("SoundFont selected. Audio engine is the next beta milestone.");}}
 void load(Uri u){songs.clear();try(BufferedReader br=new BufferedReader(new InputStreamReader(getContentResolver().openInputStream(u)))){br.readLine();String line;while((line=br.readLine())!=null){List<String> c=csv(line);if(c.size()<6)continue;try{songs.add(new Song(Integer.parseInt(c.get(0).trim()),c.get(2),c.get(3),c.get(5)));}catch(Exception ignored){}}status.setText("Catalog loaded: "+songs.size()+" songs.");}catch(Exception e){status.setText("Import failed: "+e.getMessage());}render(search.getText().toString());}
 List<String> csv(String s){ArrayList<String> o=new ArrayList<>();StringBuilder x=new StringBuilder();boolean q=false;for(int i=0;i<s.length();i++){char ch=s.charAt(i);if(ch=='\"'){if(q&&i+1<s.length()&&s.charAt(i+1)=='\"'){x.append('\"');i++;}else q=!q;}else if(ch==','&&!q){o.add(x.toString());x.setLength(0);}else x.append(ch);}o.add(x.toString());return o;}
 void render(String z){list.removeAllViews();String q=z.trim().toLowerCase(Locale.ROOT);int n=0;for(Song s:songs){String id=String.format(Locale.ROOT,"%06d",s.id);if(!q.isEmpty()&&!s.title.toLowerCase(Locale.ROOT).contains(q)&&!s.artist.toLowerCase(Locale.ROOT).contains(q)&&!id.contains(q))continue;LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(8),dp(14),dp(8));card.setBackground(bg(0xff141824,15));TextView t=tv(s.title.isEmpty()?"Untitled":s.title,17,Color.WHITE);t.setTypeface(null,1);card.addView(t);card.addView(tv("#"+id+"  •  "+(s.artist.isEmpty()?"Unknown artist":s.artist),13,0xffaab0c5));card.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(s.title).setMessage("Song #"+id+"\n"+s.artist+"\n\nMIDI: "+s.file).setPositiveButton("OK",null).show());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(8));list.addView(card,p);if(++n>=100)break;}if(songs.isEmpty())list.addView(tv("Import your catalog to begin.",14,0xff8c92a8));else if(n==0)list.addView(tv("No matching songs.",14,0xff8c92a8));}
}
